/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.School;

import School.Principal.Principal;
import School.Student.Student;
import School.Teacher.Teacher;
import System.Directories.DB4OUtil;
import System.Directories.MainSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chinm
 */
public class PrincipalWorkspace extends javax.swing.JPanel {

    /**
     * Creates new form PrincipalWorkspace
     */
    private JPanel cardPanel;
    private Principal principal;
    private MainSystem system;
    private DB4OUtil dB4OUtil;
    private final String FILENAME = "ProjectDataBank.db4o";
    
    public PrincipalWorkspace(Principal principal,JPanel cardPanel, MainSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.principal = principal;
        this.cardPanel = cardPanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        populateTeacherTable();
        populateStudentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanePrincipal = new javax.swing.JSplitPane();
        panelControl = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnApplication = new javax.swing.JButton();
        panelWork = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        panelTeacher = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTeacherName = new javax.swing.JLabel();
        lblTeacherAge = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();
        txtTeacherAge = new javax.swing.JTextField();
        btnTeacherCreate = new javax.swing.JButton();
        btnTeacherView = new javax.swing.JButton();
        ScrollPaneNgoManager = new javax.swing.JScrollPane();
        tableTeacher = new javax.swing.JTable();
        btnTeacherDelete = new javax.swing.JButton();
        lblTeacherDOB = new javax.swing.JLabel();
        txtTeacherDOB = new javax.swing.JTextField();
        lblTeacherUsername = new javax.swing.JLabel();
        txtTeacherUsername = new javax.swing.JTextField();
        lblTeacherEmailId = new javax.swing.JLabel();
        txtTeacherEmailId = new javax.swing.JTextField();
        txtTeacherPhno = new javax.swing.JTextField();
        lblTeacherPhno = new javax.swing.JLabel();
        lblTeacherPassword = new javax.swing.JLabel();
        txtTeacherPassword = new javax.swing.JPasswordField();
        btnTeacherUpdate = new javax.swing.JButton();
        lblNgoManagerId = new javax.swing.JLabel();
        txtTeacherId = new javax.swing.JTextField();
        lblTeacherSearch = new javax.swing.JLabel();
        txtTeacherSearch = new javax.swing.JTextField();
        lblTeacherGender = new javax.swing.JLabel();
        cmbTeacherGender = new javax.swing.JComboBox<>();
        lblTeacherRole = new javax.swing.JLabel();
        txtTeacherRole = new javax.swing.JTextField();
        lblTeacherEx = new javax.swing.JLabel();
        txtTeacherEx = new javax.swing.JTextField();
        panelStudent = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblTeacherAge1 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtStudentAge = new javax.swing.JTextField();
        btnStudentCreate = new javax.swing.JButton();
        btnStudentView = new javax.swing.JButton();
        ScrollPaneNgoManager1 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable();
        btnStudentDelete = new javax.swing.JButton();
        lblTeacherDOB1 = new javax.swing.JLabel();
        txtStudentDOB = new javax.swing.JTextField();
        lblStudentEmailId = new javax.swing.JLabel();
        txtStudentEmailId = new javax.swing.JTextField();
        txtStudentPhno = new javax.swing.JTextField();
        lblStudentPhno = new javax.swing.JLabel();
        btnStudentUpdate = new javax.swing.JButton();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        lblStudentSearch = new javax.swing.JLabel();
        txtStudentSearch = new javax.swing.JTextField();
        lblStudentGender = new javax.swing.JLabel();
        cmbStudentGender = new javax.swing.JComboBox<>();
        lblStudentRole = new javax.swing.JLabel();
        txtStudentRole = new javax.swing.JTextField();
        lblStudentClass = new javax.swing.JLabel();
        txtStudentClass = new javax.swing.JTextField();
        panelMarks = new javax.swing.JPanel();

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnTeacher.setText("Teacher");
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        btnStudent.setText("Student");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnApplication.setText("Applications");

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnApplication)
                .addGap(187, 187, 187)
                .addComponent(btnTeacher)
                .addGap(18, 18, 18)
                .addComponent(btnStudent)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        SplitPanePrincipal.setLeftComponent(panelControl);

        panelWork.setLayout(new java.awt.CardLayout());

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("School");

        lblRole.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblRole.setText("Role: Principal");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle2)
                .addGap(57, 57, 57)
                .addComponent(lblRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut)
                .addContainerGap(548, Short.MAX_VALUE))
        );

        panelWork.add(panelHome, "card2");

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Teacher");

        lblTeacherName.setText("Name:");

        lblTeacherAge.setText("Age:");

        btnTeacherCreate.setText("Create");
        btnTeacherCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherCreateActionPerformed(evt);
            }
        });

        btnTeacherView.setText("View");
        btnTeacherView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherViewActionPerformed(evt);
            }
        });

        tableTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Age", "Email-Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScrollPaneNgoManager.setViewportView(tableTeacher);

        btnTeacherDelete.setText("Delete");
        btnTeacherDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherDeleteActionPerformed(evt);
            }
        });

        lblTeacherDOB.setText("DOB:");

        lblTeacherUsername.setText("Username:");

        lblTeacherEmailId.setText("Email-Id:");

        lblTeacherPhno.setText("Phone No:");

        lblTeacherPassword.setText("Password:");

        btnTeacherUpdate.setText("Update");
        btnTeacherUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherUpdateActionPerformed(evt);
            }
        });

        lblNgoManagerId.setText("Teacher Id:");

        lblTeacherSearch.setText("Search:");

        lblTeacherGender.setText("Gender:");

        cmbTeacherGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        lblTeacherRole.setText("Role:");

        txtTeacherRole.setEditable(false);
        txtTeacherRole.setText("Teacher");

        lblTeacherEx.setText("Experience:");

        javax.swing.GroupLayout panelTeacherLayout = new javax.swing.GroupLayout(panelTeacher);
        panelTeacher.setLayout(panelTeacherLayout);
        panelTeacherLayout.setHorizontalGroup(
            panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addComponent(lblTeacherSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtTeacherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTeacherLayout.createSequentialGroup()
                            .addComponent(btnTeacherView)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnTeacherDelete))
                        .addComponent(ScrollPaneNgoManager, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTeacherCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTeacherUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                                .addComponent(lblNgoManagerId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTeacherName)
                                    .addComponent(lblTeacherAge)
                                    .addComponent(lblTeacherDOB)
                                    .addComponent(lblTeacherUsername))
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTeacherLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTeacherAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTeacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTeacherDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addComponent(lblTeacherRole)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTeacherRole, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTeacherPhno)
                                    .addComponent(lblTeacherPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTeacherPassword)
                                    .addComponent(txtTeacherPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeacherLayout.createSequentialGroup()
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTeacherEmailId)
                                    .addComponent(lblTeacherGender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbTeacherGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTeacherEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addGroup(panelTeacherLayout.createSequentialGroup()
                                .addComponent(lblTeacherEx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTeacherEx, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(77, 77, 77))
        );
        panelTeacherLayout.setVerticalGroup(
            panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTitle1)
                .addGap(73, 73, 73)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacherSearch)
                    .addComponent(txtTeacherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneNgoManager, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacherView)
                    .addComponent(btnTeacherDelete))
                .addGap(54, 54, 54)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgoManagerId)
                    .addComponent(txtTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherGender)
                    .addComponent(cmbTeacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherName))
                        .addGap(18, 18, 18)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherUsername))
                        .addGap(20, 20, 20)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherAge)))
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTeacherEmailId)
                            .addComponent(txtTeacherEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTeacherPhno)
                            .addComponent(txtTeacherPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTeacherEx)
                            .addComponent(txtTeacherEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeacherDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherDOB)
                    .addComponent(lblTeacherPassword)
                    .addComponent(txtTeacherPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacherRole)
                    .addComponent(txtTeacherRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacherCreate)
                    .addComponent(btnTeacherUpdate))
                .addGap(46, 46, 46))
        );

        panelWork.add(panelTeacher, "card2");

        lblTitle3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Student");

        lblStudentName.setText("Name:");

        lblTeacherAge1.setText("Age:");

        btnStudentCreate.setText("Create");
        btnStudentCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCreateActionPerformed(evt);
            }
        });

        btnStudentView.setText("View");
        btnStudentView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentViewActionPerformed(evt);
            }
        });

        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Class", "Age", "Email-Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScrollPaneNgoManager1.setViewportView(tableStudent);

        btnStudentDelete.setText("Delete");
        btnStudentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentDeleteActionPerformed(evt);
            }
        });

        lblTeacherDOB1.setText("DOB:");

        lblStudentEmailId.setText("Email-Id:");

        lblStudentPhno.setText("Phone No:");

        btnStudentUpdate.setText("Update");
        btnStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentUpdateActionPerformed(evt);
            }
        });

        lblStudentId.setText("Student Id:");

        lblStudentSearch.setText("Search:");

        lblStudentGender.setText("Gender:");

        cmbStudentGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        lblStudentRole.setText("Role:");

        txtStudentRole.setEditable(false);
        txtStudentRole.setText("Student");

        lblStudentClass.setText("Class:");

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addComponent(lblStudentSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelStudentLayout.createSequentialGroup()
                            .addComponent(btnStudentView)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnStudentDelete))
                        .addComponent(ScrollPaneNgoManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStudentCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStudentUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelStudentLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelStudentLayout.createSequentialGroup()
                                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                                                .addComponent(lblStudentId)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelStudentLayout.createSequentialGroup()
                                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(panelStudentLayout.createSequentialGroup()
                                                        .addComponent(lblStudentName)
                                                        .addGap(21, 21, 21)
                                                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtStudentDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(panelStudentLayout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addComponent(txtStudentRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(txtStudentClass, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(panelStudentLayout.createSequentialGroup()
                                                        .addComponent(lblStudentClass)
                                                        .addGap(277, 277, 277)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(55, 55, 55))
                                    .addGroup(panelStudentLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblTeacherAge1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(panelStudentLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblStudentRole)
                                    .addComponent(lblTeacherDOB1))
                                .addGap(332, 332, 332)))
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelStudentLayout.createSequentialGroup()
                                .addComponent(lblStudentPhno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(txtStudentPhno, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentEmailId)
                                    .addComponent(lblStudentGender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbStudentGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStudentEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))))
                .addGap(77, 77, 77))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTitle3)
                .addGap(73, 73, 73)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentSearch)
                    .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneNgoManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentView)
                    .addComponent(btnStudentDelete))
                .addGap(54, 54, 54)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentGender)
                    .addComponent(cmbStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentName))
                        .addGap(18, 18, 18)
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTeacherAge1)
                            .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentEmailId)
                            .addComponent(txtStudentEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentPhno)
                            .addComponent(txtStudentPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeacherDOB1))))
                .addGap(20, 20, 20)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentRole))
                .addGap(18, 18, 18)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentCreate)
                    .addComponent(btnStudentUpdate))
                .addGap(26, 26, 26))
        );

        panelWork.add(panelStudent, "card2");

        javax.swing.GroupLayout panelMarksLayout = new javax.swing.GroupLayout(panelMarks);
        panelMarks.setLayout(panelMarksLayout);
        panelMarksLayout.setHorizontalGroup(
            panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        panelMarksLayout.setVerticalGroup(
            panelMarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        panelWork.add(panelMarks, "card4");

        SplitPanePrincipal.setRightComponent(panelWork);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanePrincipal)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeacherCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherCreateActionPerformed
        // TODO add your handling code here:

        String id = txtTeacherId.getText();
        String name = txtTeacherName.getText();
        String username = txtTeacherUsername.getText();
        Integer age = Integer.valueOf(txtTeacherAge.getText());
        String dob = txtTeacherDOB.getText();
        String gender = String.valueOf(cmbTeacherGender.getSelectedItem());
        String role = txtTeacherRole.getText();
        String emailid= txtTeacherEmailId.getText();
        Long phno = Long.valueOf(txtTeacherPhno.getText());
        Integer experience = Integer.valueOf(txtTeacherEx.getText());
        String pass = txtTeacherPassword.getText();

        Teacher newTeacher = system.getTeacherList().addTeacher();

        newTeacher.setTeacherId(id);
        newTeacher.setName(name);
        newTeacher.setUsername(username);
        newTeacher.setAge(age);
        newTeacher.setDob(dob);
        newTeacher.setGender(gender);
        newTeacher.setRole(role);
        newTeacher.setEmailId(emailid);
        newTeacher.setPhno(phno);
        newTeacher.setExperience(experience);
        newTeacher.setPassword(pass);

        JOptionPane.showMessageDialog(this, "Teacher created successfully");

        txtTeacherId.setText("");
        txtTeacherName.setText("");
        txtTeacherUsername.setText("");
        txtTeacherAge.setText("");
        txtTeacherDOB.setText("");
        txtTeacherEmailId.setText("");
        txtTeacherPhno.setText("");
        txtTeacherEx.setText("");
        txtTeacherPassword.setText("");

        //        dB4OUtil.storeSystem(system);
        populateTeacherTable();
    }//GEN-LAST:event_btnTeacherCreateActionPerformed

    private void btnTeacherViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherViewActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableTeacher.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            Teacher selMan = (Teacher) model.getValueAt(selectedRowIndex,0);

            txtTeacherId.setText(selMan.getTeacherId());
            txtTeacherName.setText(selMan.getName());
            txtTeacherUsername.setText(selMan.getUsername());
            txtTeacherAge.setText(String.valueOf(selMan.getAge()));
            txtTeacherDOB.setText(selMan.getDob());
            cmbTeacherGender.setSelectedItem(selMan.getGender());
            txtTeacherRole.setText(selMan.getRole());
            txtTeacherEmailId.setText(selMan.getEmailId());
            txtTeacherPhno.setText(String.valueOf(selMan.getPhno()));
            txtTeacherEx.setText(String.valueOf(selMan.getExperience()));
            txtTeacherPassword.setText(selMan.getPassword());

        }
    }//GEN-LAST:event_btnTeacherViewActionPerformed

    private void btnTeacherDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherDeleteActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableTeacher.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            Teacher selectedMan = (Teacher) model.getValueAt(selectedRowIndex,0);

            system.getTeacherList().deleteTeacher(selectedMan);

            JOptionPane.showMessageDialog(this, "Teacher deleted successfully.");

            //            dB4OUtil.storeSystem(system);
            populateTeacherTable();
        }
    }//GEN-LAST:event_btnTeacherDeleteActionPerformed

    private void btnTeacherUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherUpdateActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableTeacher.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
            Teacher selMan = (Teacher) model.getValueAt(selectedRowIndex,0);

            selMan.setTeacherId(txtTeacherId.getText());
            selMan.setName(txtTeacherName.getText());
            selMan.setUsername(txtTeacherUsername.getText());
            selMan.setAge(Integer.valueOf(txtTeacherAge.getText()));
            selMan.setDob(txtTeacherDOB.getText());
            selMan.setGender(String.valueOf(cmbTeacherGender.getSelectedItem()));
            selMan.setRole(txtTeacherRole.getText());
            selMan.setEmailId(txtTeacherEmailId.getText());
            selMan.setPhno(Long.valueOf(txtTeacherPhno.getText()));
            selMan.setExperience(Integer.valueOf(txtTeacherEx.getText()));
            selMan.setPassword(txtTeacherPassword.getText());

            JOptionPane.showMessageDialog(this, "Teacher updated successfully");

            //            dB4OUtil.storeSystem(system);
            populateTeacherTable();

        }
    }//GEN-LAST:event_btnTeacherUpdateActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelHome);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelTeacher);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.remove(this);
        cardLayout.previous(cardPanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        panelWork.removeAll();
        panelWork.add(panelStudent);
        panelWork.repaint();
        panelWork.revalidate();
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnStudentCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCreateActionPerformed
        // TODO add your handling code here:
        String id = txtStudentId.getText();
        String name = txtStudentName.getText();
        Integer age = Integer.valueOf(txtStudentAge.getText());
        String dob = txtStudentDOB.getText();
        String gender = String.valueOf(cmbStudentGender.getSelectedItem());
        String role = txtStudentRole.getText();
        String cls = txtStudentClass.getText();
        String emailid= txtStudentEmailId.getText();
        Long phno = Long.valueOf(txtStudentPhno.getText());

        Student newStudent = system.getStudentList().addStudent();

        newStudent.setStudentId(id);
        newStudent.setName(name);
        newStudent.setAge(age);
        newStudent.setDob(dob);
        newStudent.setGender(gender);
        newStudent.setRole(role);
        newStudent.setCls(cls);
        newStudent.setEmailId(emailid);
        newStudent.setPhno(phno);

        JOptionPane.showMessageDialog(this, "Student created successfully");

        txtStudentId.setText("");
        txtStudentName.setText("");

        txtStudentAge.setText("");
        txtStudentDOB.setText("");
        txtStudentClass.setText("");
        txtStudentEmailId.setText("");
        txtStudentPhno.setText("");

        //        dB4OUtil.storeSystem(system);
        populateStudentTable();
    }//GEN-LAST:event_btnStudentCreateActionPerformed

    private void btnStudentViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentViewActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableStudent.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
            Student selMan = (Student) model.getValueAt(selectedRowIndex,0);

            txtStudentId.setText(selMan.getStudentId());
            txtStudentName.setText(selMan.getName());

            txtStudentAge.setText(String.valueOf(selMan.getAge()));
            txtStudentDOB.setText(selMan.getDob());
            cmbStudentGender.setSelectedItem(selMan.getGender());
            txtStudentRole.setText(selMan.getRole());
            txtStudentClass.setText(selMan.getCls());
            txtStudentEmailId.setText(selMan.getEmailId());
            txtStudentPhno.setText(String.valueOf(selMan.getPhno()));

        }
    }//GEN-LAST:event_btnStudentViewActionPerformed

    private void btnStudentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentDeleteActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableStudent.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
            Student selectedMan = (Student) model.getValueAt(selectedRowIndex,0);

            system.getStudentList().deleteStudent(selectedMan);

            JOptionPane.showMessageDialog(this, "Student deleted successfully.");

            //            dB4OUtil.storeSystem(system);
            populateStudentTable();
        }
    }//GEN-LAST:event_btnStudentDeleteActionPerformed

    private void btnStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentUpdateActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableStudent.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
            Student selMan = (Student) model.getValueAt(selectedRowIndex,0);

            selMan.setStudentId(txtStudentId.getText());
            selMan.setName(txtStudentName.getText());

            selMan.setAge(Integer.valueOf(txtStudentAge.getText()));
            selMan.setDob(txtStudentDOB.getText());
            selMan.setGender(String.valueOf(cmbStudentGender.getSelectedItem()));
            selMan.setRole(txtStudentRole.getText());
            selMan.setCls(txtStudentClass.getText());
            selMan.setEmailId(txtStudentEmailId.getText());
            selMan.setPhno(Long.valueOf(txtStudentPhno.getText()));

            JOptionPane.showMessageDialog(this, "Student updated successfully");

            //            dB4OUtil.storeSystem(system);
            populateTeacherTable();
        }
    }//GEN-LAST:event_btnStudentUpdateActionPerformed

       private void populateTeacherTable(){
        DefaultTableModel model = (DefaultTableModel) tableTeacher.getModel();
        model.setRowCount(0);
        
//        
            for(Teacher man: system.getTeacherList().getTeacherList()){

                Object[] row = new Object[5];
                row[0] = man; 
                row[1] = man.getName();
                row[2] = man.getUsername();
                row[3] = man.getAge();
                row[4] = man.getEmailId();
                model.addRow(row);
            }
    }
    
    private void populateStudentTable(){
        DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
        model.setRowCount(0);
        
//        
            for(Student man: system.getStudentList().getStudentList()){

                Object[] row = new Object[5];
                row[0] = man; 
                row[1] = man.getName();
                row[2] = man.getCls();
                row[3] = man.getAge();
                row[4] = man.getEmailId();
                model.addRow(row);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneNgoManager;
    private javax.swing.JScrollPane ScrollPaneNgoManager1;
    private javax.swing.JSplitPane SplitPanePrincipal;
    private javax.swing.JButton btnApplication;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnStudentCreate;
    private javax.swing.JButton btnStudentDelete;
    private javax.swing.JButton btnStudentUpdate;
    private javax.swing.JButton btnStudentView;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JButton btnTeacherCreate;
    private javax.swing.JButton btnTeacherDelete;
    private javax.swing.JButton btnTeacherUpdate;
    private javax.swing.JButton btnTeacherView;
    private javax.swing.JComboBox<String> cmbStudentGender;
    private javax.swing.JComboBox<String> cmbTeacherGender;
    private javax.swing.JLabel lblNgoManagerId;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStudentClass;
    private javax.swing.JLabel lblStudentEmailId;
    private javax.swing.JLabel lblStudentGender;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentPhno;
    private javax.swing.JLabel lblStudentRole;
    private javax.swing.JLabel lblStudentSearch;
    private javax.swing.JLabel lblTeacherAge;
    private javax.swing.JLabel lblTeacherAge1;
    private javax.swing.JLabel lblTeacherDOB;
    private javax.swing.JLabel lblTeacherDOB1;
    private javax.swing.JLabel lblTeacherEmailId;
    private javax.swing.JLabel lblTeacherEx;
    private javax.swing.JLabel lblTeacherGender;
    private javax.swing.JLabel lblTeacherName;
    private javax.swing.JLabel lblTeacherPassword;
    private javax.swing.JLabel lblTeacherPhno;
    private javax.swing.JLabel lblTeacherRole;
    private javax.swing.JLabel lblTeacherSearch;
    private javax.swing.JLabel lblTeacherUsername;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMarks;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel panelTeacher;
    private javax.swing.JPanel panelWork;
    private javax.swing.JTable tableStudent;
    private javax.swing.JTable tableTeacher;
    private javax.swing.JTextField txtStudentAge;
    private javax.swing.JTextField txtStudentClass;
    private javax.swing.JTextField txtStudentDOB;
    private javax.swing.JTextField txtStudentEmailId;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentPhno;
    private javax.swing.JTextField txtStudentRole;
    private javax.swing.JTextField txtStudentSearch;
    private javax.swing.JTextField txtTeacherAge;
    private javax.swing.JTextField txtTeacherDOB;
    private javax.swing.JTextField txtTeacherEmailId;
    private javax.swing.JTextField txtTeacherEx;
    private javax.swing.JTextField txtTeacherId;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JPasswordField txtTeacherPassword;
    private javax.swing.JTextField txtTeacherPhno;
    private javax.swing.JTextField txtTeacherRole;
    private javax.swing.JTextField txtTeacherSearch;
    private javax.swing.JTextField txtTeacherUsername;
    // End of variables declaration//GEN-END:variables
}
