/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.Ngo;

import Ngo.NgoManager.NgoManager;
import System.Directories.DB4OUtil;
import System.Directories.MainSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chinm
 */
public class NgoAdminWorkspace extends javax.swing.JPanel {

    /**
     * Creates new form NgoAdminWorkspace
     */
    
    private JPanel cardPanel;
    private MainSystem system;
    private DB4OUtil dB4OUtil;
//    private NgoManagerDirectory ngoManagerList;
    private final String FILENAME = "ProjectDataBank.db4o";
    
    public NgoAdminWorkspace(JPanel cardPanel, MainSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.cardPanel = cardPanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
//        this.ngoManagerList = ngoManagerList;
        populateTable();
//        retrieveData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneAdmin = new javax.swing.JSplitPane();
        panelAdminControl = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnNgoManager = new javax.swing.JButton();
        btnHealth = new javax.swing.JButton();
        btnEducation = new javax.swing.JButton();
        btnBudget = new javax.swing.JButton();
        btnCaretaker = new javax.swing.JButton();
        panelAdminWork = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        panelNgoManager = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNgoManager = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        panelCareTaker = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnNgoManager.setText("NGO Manager");
        btnNgoManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgoManagerActionPerformed(evt);
            }
        });

        btnHealth.setText("Health");

        btnEducation.setText("Education");

        btnBudget.setText("Budget");
        btnBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBudgetActionPerformed(evt);
            }
        });

        btnCaretaker.setText("Caretaker");
        btnCaretaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaretakerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminControlLayout = new javax.swing.GroupLayout(panelAdminControl);
        panelAdminControl.setLayout(panelAdminControlLayout);
        panelAdminControlLayout.setHorizontalGroup(
            panelAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCaretaker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEducation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminControlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(btnHealth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnNgoManager, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelAdminControlLayout.setVerticalGroup(
            panelAdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminControlLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnHealth)
                .addGap(18, 18, 18)
                .addComponent(btnEducation)
                .addGap(18, 18, 18)
                .addComponent(btnBudget)
                .addGap(130, 130, 130)
                .addComponent(btnNgoManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaretaker)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        SplitPaneAdmin.setLeftComponent(panelAdminControl);

        panelAdminWork.setLayout(new java.awt.CardLayout());

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("NGO");

        lblRole.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblRole.setText("Role: NGO Admin");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle2)
                .addGap(57, 57, 57)
                .addComponent(lblRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        panelAdminWork.add(panelHome, "card3");

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("NGO Manager");

        lblName.setText("Name:");

        lblAge.setText("Age:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tableNgoManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableNgoManager);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNgoManagerLayout = new javax.swing.GroupLayout(panelNgoManager);
        panelNgoManager.setLayout(panelNgoManagerLayout);
        panelNgoManagerLayout.setHorizontalGroup(
            panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNgoManagerLayout.createSequentialGroup()
                .addGroup(panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNgoManagerLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelNgoManagerLayout.createSequentialGroup()
                                .addGroup(panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblAge))
                                .addGap(52, 52, 52)
                                .addGroup(panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelNgoManagerLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnCreate)
                                .addGap(38, 38, 38)
                                .addComponent(btnView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete))))
                    .addGroup(panelNgoManagerLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
            .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelNgoManagerLayout.setVerticalGroup(
            panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNgoManagerLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTitle1)
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(panelNgoManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addGap(93, 93, 93))
        );

        panelAdminWork.add(panelNgoManager, "card2");

        lblTitle3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Caretaker");

        jLabel1.setText("Name:");

        javax.swing.GroupLayout panelCareTakerLayout = new javax.swing.GroupLayout(panelCareTaker);
        panelCareTaker.setLayout(panelCareTakerLayout);
        panelCareTakerLayout.setHorizontalGroup(
            panelCareTakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCareTakerLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addContainerGap(636, Short.MAX_VALUE))
        );
        panelCareTakerLayout.setVerticalGroup(
            panelCareTakerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCareTakerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle3)
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        panelAdminWork.add(panelCareTaker, "card4");

        SplitPaneAdmin.setRightComponent(panelAdminWork);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneAdmin)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNgoManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgoManagerActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) panelAdminWork.getLayout();
        panelAdminWork.add("NgoManager", panelNgoManager);
        cardLayout.next(panelAdminWork);
    }//GEN-LAST:event_btnNgoManagerActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        String name = txtName.getText();
        String age = txtAge.getText();
        
        NgoManager newManager = system.getNgoManagerList().addNgoManager();
        
        newManager.setName(name);
        newManager.setAge(age);
        
        JOptionPane.showMessageDialog(this, "NGO Manager created successfully");
        
        txtName.setText("");
        txtAge.setText("");
        
        dB4OUtil.storeSystem(system);
//        String FILENAME = Paths.get("DataBank1.db4o").toAbsolutePath().toString();
//        ObjectContainer db = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), FILENAME);
//        
//       
//        db.store(newManager);
//        db.store();
//        db.close();
        populateTable();
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardPanel.remove(this);
        cardLayout.previous(cardPanel);
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) panelAdminWork.getLayout();
        panelAdminWork.add("NgoHome", panelHome);
        cardLayout.next(panelAdminWork);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         Integer selectedRowIndex = tableNgoManager.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableNgoManager.getModel();
            NgoManager selMan = (NgoManager) model.getValueAt(selectedRowIndex,0);
            
            txtName.setText(selMan.getName());
            txtAge.setText(selMan.getAge());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBudgetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          Integer selectedRowIndex = tableNgoManager.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableNgoManager.getModel();
            NgoManager selectedMan = (NgoManager) model.getValueAt(selectedRowIndex,0);

            system.getNgoManagerList().deleteNgoManager(selectedMan);

            JOptionPane.showMessageDialog(this, "NGO Manager deleted successfully.");
            
            dB4OUtil.storeSystem(system);
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCaretakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaretakerActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) panelAdminWork.getLayout();
        panelAdminWork.add("CareTaker", panelCareTaker);
        cardLayout.next(panelAdminWork);
    }//GEN-LAST:event_btnCaretakerActionPerformed

//    public void listResult(ObjectSet result){
//        System.out.println(result.size());
//        while(result.hasNext()){
//            System.out.println(result.next());
//            if(result.next() instanceof ArrayList)
//            System.out.println(result.next().getClass().getSimpleName());
//        }
//    }
//    
//    public void retrieveData(){
//       
//        ObjectContainer db = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), FILENAME);
//        ObjectSet result = db.queryByExample(ngoManagerList);
//        listResult(result);
//        db.close();
//    }
    private void populateTable(){
//        ObjectContainer db = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), FILENAME);
//        ObjectSet result = db.queryByExample(ngoManagerList);
//        System.out.println(result.size());
//        while(result.hasNext()){
        
//        }
//        db.close();
        
        DefaultTableModel model = (DefaultTableModel) tableNgoManager.getModel();
        model.setRowCount(0);
        
//        while(result.hasNext()){
//            NgoManagerDirectory getItem = (NgoManagerDirectory) result.next();
//            System.out.println(getItem);
            for(NgoManager man: system.getNgoManagerList().getNgoManagerList()){

                Object[] row = new Object[2];
                row[0] = man; 
                row[1] = man.getAge();
                model.addRow(row);
            }
//        }
//        db.close();
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPaneAdmin;
    private javax.swing.JButton btnBudget;
    private javax.swing.JButton btnCaretaker;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEducation;
    private javax.swing.JButton btnHealth;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNgoManager;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JPanel panelAdminControl;
    private javax.swing.JPanel panelAdminWork;
    private javax.swing.JPanel panelCareTaker;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelNgoManager;
    private javax.swing.JTable tableNgoManager;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
